module.exports = {
    
    all_clinics: 'database/slot/retrieve/clinic',                      
    clinic_dentists: 'database/slot/retrieve/dentist/from/clinic',     
    clinic_dentist_slots: 'database/slot/retrieve/reference/code',     
    dentist_new_slots: 'database/slot/found/special/clinic',           
    appointment_info: 'database/slot/found/special/dentist',           
    database_request_dentists: 'database/request/dentists/available',
    database_response_dentists: 'database/response/dentists/available',
    database_request_slots: 'database/request/slots/available',
    database_response_slots: 'database/response/slots/available',
    database_request_reserve: 'database/request/reserve',
    database_response_reserve: 'database/response/reserve',
    database_request_book_slot: 'database/request/book/slot',
    database_response_book_slot: 'database/response/book/slot',
    database_request_reference_code: 'database/request/reference-code',
    database_response_reference_code: 'database/response/reference-code',
    database_request_delete_reference_code: 'database/request/delete/reference-code',
    database_response_delete_reference_code: 'database/response/delete/reference-code',
}